name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Correct placement for the http package
  http: ^1.2.2
  intl_utils: ^2.8.7
  weather: ^3.1.1
  geolocator: ^13.0.1
  country_picker: ^2.0.26

  # Cupertino icons package for iOS style icons
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
